---
apiVersion: v1
kind: Service
metadata:
  name: spos-auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind:  AuthService
      name:  authentication
      auth_service: "spos-auth:3001"
      path_prefix: "/extauth"
      allowed_headers:
      - "x-qotm-session"
spec:
  type: NodePort
  selector:
    app: spos-auth
  ports:
  - port: 3001
    name: http-spos-auth
    targetPort: http-spos-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spos-auth
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spos-auth
    spec:
      containers:
      - name: spos-auth
        image: spos-auth:v1
        ports:
        - name: http-spos-api
          containerPort: 3001

