---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: greeter-server
  name: greeter-server
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: grpc_mapping
      grpc: true
      prefix: /spos.Greeter/
      rewrite: /spos.Greeter/
      service: greeter-server
spec:
  type: NodePort
  ports:
  - port: 80
    name: greeter-server
    targetPort: grpc-api
  selector:
    service: greeter-server
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greeter-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: greeter-server
    spec:
      containers:
      - name: greeter-server
        image: patlihh/greeter-server:v1
        ports:
        - name: grpc-api
          containerPort: 9999
        env:
          - name: PORT
            value: "9999"
#        command:
#          - greeter_server
      restartPolicy: Always
