---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: spos-lang
  name: spos-lang
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: spos_mapping
      grpc: true
      prefix: /spos.Spos/
      rewrite: /spos.Spos/
      service: spos-lang
spec:
  type: NodePort
  ports:
  - port: 80
    name: spos-lang
    targetPort: spos-api
  selector:
    service: spos-lang
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spos-lang
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: spos-lang
    spec:
      containers:
      - name: spos-lang
        image: patlihh/spos-lang:v1
        ports:
        - name: spos-api
          containerPort: 9998
        env:
          - name: PORT
            value: "9998"
      restartPolicy: Always
